version: '3.8'

services:
  pfit-import-empresas:
    build:
      context: ./importEmpresas
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./importEmpresas/src:/app/src
      - ./importEmpresas/package.json:/app/package.json
    restart: "no"  # Job executa uma vez e para
    
    # Para testar o job, descomente:
    # command: npm run dev

  # Opcional: PostgreSQL local para testes
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: